### ISSUE TITLE
Using  `lib/auth` as `packages/auth` in monorepo not working

### ISSUE THREAD

**Issue by jpainam** [leerob/next-saas-starter#75]
I'm using a monorepo and was wandering if i could move `lib/auth` in a `packages/auth`.  
My `packages/api` which is just (`trpc procedures`) needs to use `getSession()`  from `packages/auth`. Unfortunately, I'm faced with this issue

```tsx
Error: `cookies` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
    at getExpectedRequestStore (/node_modules/next/dist/server/app-render/work-unit-async-storage.external.js:48:11)
    at cookies (apps/nextjs/.next/server/chunks/08b5e_next_a123c7._.js:6593:84)
    at getUser (//apps/nextjs/.next/server/chunks/[root of the server]__510ad3._.js:1035:179)
    at auth (/apps/nextjs/.next/server/chunks/[root of the server]__510ad3._.js:1026:24)
    at [project]/apps/nextjs/src/app/api/trpc/[trpc]/route.ts [app-route] (ecmascript) 
apps/nextjs/.next/server/chunks/[root of the server]__510ad3._.js:10530:162)
    at instantiateModule (/apps/nextjs/.next/server/chunks/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (
/apps/nextjs/.next/server/chunks/[turbopack]_runtime.js:644:12)
    at esmImport (apps/nextjs/.next/server/chunks/[turbopack]_runtime.js:132:20)
    at [project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => "[project]/apps/nextjs/src/app/api/trpc/[trpc]/route.ts [app-route] (ecmascript)" } [app-route] (ecmascript) (/apps/nextjs/.next/server/chunks/[project]__e2fc59._.js:25:172)
    at instantiateModule (apps/nextjs/.next/server/chunks/[turbopack]_runtime.js:589:23)
```

This issue causes `TRPCClientError`

```tsx
TRPCClientError: Invalid response or stream interrupted
    at TRPCClientError.from (http://localhost:3000/_next/static/chunks/08b5e_ef6448._.js:4868:16)
    at http://localhost:3000/_next/static/chunks/08b5e_ef6448._.js:5755:215
```

Has anyone ever used `cookie` authorization with `monrepo`.

It's working fine with `next-auth` see https://github.com/t3-oss/create-t3-turbo/.

**Comment by jpainam** [comment]
Solve it.

Just needed to rewrite the `handler` from in `/api/trpc/[trpc]/route.ts`
